runtime: python39

entrypoint: gunicorn -b :$PORT sim_management.wsgi

env_variables:
  DJANGO_SETTINGS_MODULE: "sim_management.settings"

instance_class: F2

handlers:
  - url: /static
    static_dir: static/

  - url: /media
    static_dir: media/

  - url: /.*
    script: auto

