# Generated by Django 5.1.3 on 2024-11-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimDaBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_thue_bao', models.CharField(max_length=15)),
                ('gia_thu_goc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gia_chiet_khau', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phi_giao_dich', models.DecimalField(decimal_places=2, max_digits=10)),
                ('thuc_thu', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ngay_ban', models.DateField()),
                ('nguoi_ban', models.CharField(max_length=50)),
                ('nha_mang', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SimTonKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_thue_bao', models.CharField(max_length=15)),
                ('gia_thu_goc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gia_chiet_khau', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nha_mang', models.CharField(max_length=50)),
            ],
        ),
    ]
