# Generated by Django 5.1.3 on 2024-11-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim_inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simdaban',
            name='id',
        ),
        migrations.RemoveField(
            model_name='simtonkho',
            name='id',
        ),
        migrations.AddField(
            model_name='simdaban',
            name='so_thu_tu',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='simtonkho',
            name='so_thu_tu',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
