# Generated by Django 5.1.3 on 2024-12-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim_inventory', '0002_remove_simdaban_id_remove_simtonkho_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simtonkho',
            name='trang_thai',
            field=models.CharField(choices=[('Còn', 'Còn'), ('Đã bán', 'Đã bán')], default='Còn', max_length=10),
        ),
    ]
