# Generated by Django 5.1.3 on 2024-12-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim_inventory', '0003_simtonkho_trang_thai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simdaban',
            name='so_thu_tu',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='simdaban',
            name='so_thue_bao',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='simtonkho',
            name='so_thu_tu',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='simtonkho',
            name='so_thue_bao',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
