# Generated by Django 5.1.3 on 2024-12-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim_inventory', '0004_alter_simdaban_so_thu_tu_alter_simdaban_so_thue_bao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simtonkho',
            name='ngay_ban',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simtonkho',
            name='nguoi_ban',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='simtonkho',
            name='phi_giao_dich',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
