# Generated by Django 5.1.3 on 2024-12-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim_inventory', '0005_simtonkho_ngay_ban_simtonkho_nguoi_ban_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simdaban',
            name='gia_chiet_khau',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='simdaban',
            name='gia_thu_goc',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='simdaban',
            name='phi_giao_dich',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='simtonkho',
            name='gia_chiet_khau',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='simtonkho',
            name='gia_thu_goc',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='simtonkho',
            name='phi_giao_dich',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
