# Generated by Django 5.1.3 on 2024-12-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim_inventory', '0006_alter_simdaban_gia_chiet_khau_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simdaban',
            name='thuc_thu',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
